namespace AsciiToSvg.Tests

module LineScanner =

  open AsciiToSvg
  open AsciiToSvg.Tests.TxtFile


  module ArrowGlyph_txt =

    let horizLines = ArrowGlyph_txt.makeGridResult |> LineScanner.ScanLineHorizontally
    let vertLines = ArrowGlyph_txt.makeGridResult |> LineScanner.ScanLineVertically
    let allLines = ArrowGlyph_txt.makeGridResult |> LineScanner.ScanLine

    let allLinesExpected =
      ([|{ orientation = Horizontal
           gridCoordStart = { col = 27; row = 1 }
           gridCoordEnd = { col = 27; row = 1 }
           linechars = [|'-'|]
           lineOptions = Map.empty };
         { orientation = Horizontal
           gridCoordStart = { col = 46; row = 1 }
           gridCoordEnd = { col = 46; row = 1 }
           linechars = [|'-'|]
           lineOptions = Map.empty };
         { orientation = Horizontal
           gridCoordStart = { col = 27; row = 2 }
           gridCoordEnd = { col = 27; row = 2}
           linechars = [|'+'|]
           lineOptions = Map.empty };
         { orientation = Horizontal
           gridCoordStart = { col = 46; row = 2 }
           gridCoordEnd = { col = 46; row = 2 }
           linechars = [|'+'|]
           lineOptions = Map.empty }|],
       [|{ orientation = Vertical
           gridCoordStart = { col = 1; row = 2 }
           gridCoordEnd = { col = 1; row = 2 }
           linechars = [|'|'|]
           lineOptions = Map.empty };
         { orientation = Vertical
           gridCoordStart = {col = 5; row = 2 }
           gridCoordEnd = { col = 5; row = 2 }
           linechars = [|'+'|]
           lineOptions = Map.empty };
         { orientation = Vertical
           gridCoordStart = { col = 12; row = 1 }
           gridCoordEnd = { col = 12; row = 1 }
           linechars = [|'|'|]
           lineOptions = Map.empty };
         { orientation = Vertical
           gridCoordStart = {col = 16; row = 1 }
           gridCoordEnd = { col = 16; row = 1 }
           linechars = [|'+'|]
           lineOptions = Map.empty }|])

    let lineScanResult = (horizLines, vertLines) = allLinesExpected && allLinesExpected = allLines

  module ArrowGlyphWithFrame_txt =

    let horizLines = ArrowGlyphWithFrame_txt.makeGridResult |> LineScanner.ScanLineHorizontally
    let vertLines = ArrowGlyphWithFrame_txt.makeGridResult |> LineScanner.ScanLineVertically
    let allLines = ArrowGlyphWithFrame_txt.makeGridResult |> LineScanner.ScanLine

    let allLinesExpected =
      ([| { orientation = Horizontal
            gridCoordStart =
              { col = 1
                row = 0 }
            gridCoordEnd =
              { col = 9
                row = 0 }
            linechars = [| '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-' |]
            lineOptions = Map.empty }
          { orientation = Horizontal
            gridCoordStart =
              { col = 11
                row = 0 }
            gridCoordEnd =
              { col = 21
                row = 0 }
            linechars = [| '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-' |]
            lineOptions = Map.empty }
          { orientation = Horizontal
            gridCoordStart =
              { col = 23
                row = 0 }
            gridCoordEnd =
              { col = 40
                row = 0 }
            linechars = [| '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-' |]
            lineOptions = Map.empty }
          { orientation = Horizontal
            gridCoordStart =
              { col = 42
                row = 0 }
            gridCoordEnd =
              { col = 59
                row = 0 }
            linechars = [| '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-' |]
            lineOptions = Map.empty }
          { orientation = Horizontal
            gridCoordStart =
              { col = 1
                row = 2 }
            gridCoordEnd =
              { col = 9
                row = 2 }
            linechars = [| '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-' |]
            lineOptions = Map.empty }
          { orientation = Horizontal
            gridCoordStart =
              { col = 11
                row = 2 }
            gridCoordEnd =
              { col = 21
                row = 2 }
            linechars = [| '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-' |]
            lineOptions = Map.empty }
          { orientation = Horizontal
            gridCoordStart =
              { col = 23
                row = 2 }
            gridCoordEnd =
              { col = 40
                row = 2 }
            linechars = [| '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-' |]
            lineOptions = Map.empty }
          { orientation = Horizontal
            gridCoordStart =
              { col = 42
                row = 2 }
            gridCoordEnd =
              { col = 59
                row = 2 }
            linechars = [| '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-' |]
            lineOptions = Map.empty }
          { orientation = Horizontal
            gridCoordStart =
              { col = 31
                row = 3 }
            gridCoordEnd =
              { col = 31
                row = 3 }
            linechars = [| '-' |]
            lineOptions = Map.empty }
          { orientation = Horizontal
            gridCoordStart =
              { col = 51
                row = 3 }
            gridCoordEnd =
              { col = 51
                row = 3 }
            linechars = [| '-' |]
            lineOptions = Map.empty }
          { orientation = Horizontal
            gridCoordStart =
              { col = 31
                row = 4 }
            gridCoordEnd =
              { col = 31
                row = 4 }
            linechars = [| '+' |]
            lineOptions = Map.empty }
          { orientation = Horizontal
            gridCoordStart =
              { col = 51
                row = 4 }
            gridCoordEnd =
              { col = 51
                row = 4 }
            linechars = [| '+' |]
            lineOptions = Map.empty }
          { orientation = Horizontal
            gridCoordStart =
              { col = 1
                row = 5 }
            gridCoordEnd =
              { col = 9
                row = 5 }
            linechars = [| '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-' |]
            lineOptions = Map.empty }
          { orientation = Horizontal
            gridCoordStart =
              { col = 11
                row = 5 }
            gridCoordEnd =
              { col = 21
                row = 5 }
            linechars = [| '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-' |]
            lineOptions = Map.empty }
          { orientation = Horizontal
            gridCoordStart =
              { col = 23
                row = 5 }
            gridCoordEnd =
              { col = 40
                row = 5 }
            linechars = [| '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-' |]
            lineOptions = Map.empty }
          { orientation = Horizontal
            gridCoordStart =
              { col = 42
                row = 5 }
            gridCoordEnd =
              { col = 59
                row = 5 }
            linechars = [| '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-'; '-' |]
            lineOptions = Map.empty } |],
       [| { orientation = Vertical
            gridCoordStart =
              { col = 0
                row = 1 }
            gridCoordEnd =
              { col = 0
                row = 1 }
            linechars = [| '|' |]
            lineOptions = Map.empty }
          { orientation = Vertical
            gridCoordStart =
              { col = 0
                row = 3 }
            gridCoordEnd =
              { col = 0
                row = 4 }
            linechars = [| '|'; '|' |]
            lineOptions = Map.empty }
          { orientation = Vertical
            gridCoordStart =
              { col = 3
                row = 4 }
            gridCoordEnd =
              { col = 3
                row = 4 }
            linechars = [| '|' |]
            lineOptions = Map.empty }
          { orientation = Vertical
            gridCoordStart =
              { col = 7
                row = 4 }
            gridCoordEnd =
              { col = 7
                row = 4 }
            linechars = [| '+' |]
            lineOptions = Map.empty }
          { orientation = Vertical
            gridCoordStart =
              { col = 10
                row = 1 }
            gridCoordEnd =
              { col = 10
                row = 1 }
            linechars = [| '|' |]
            lineOptions = Map.empty }
          { orientation = Vertical
            gridCoordStart =
              { col = 10
                row = 3 }
            gridCoordEnd =
              { col = 10
                row = 4 }
            linechars = [| '|'; '|' |]
            lineOptions = Map.empty }
          { orientation = Vertical
            gridCoordStart =
              { col = 15
                row = 3 }
            gridCoordEnd =
              { col = 15
                row = 3 }
            linechars = [| '|' |]
            lineOptions = Map.empty }
          { orientation = Vertical
            gridCoordStart =
              { col = 19
                row = 3 }
            gridCoordEnd =
              { col = 19
                row = 3 }
            linechars = [| '+' |]
            lineOptions = Map.empty }
          { orientation = Vertical
            gridCoordStart =
              { col = 22
                row = 1 }
            gridCoordEnd =
              { col = 22
                row = 1 }
            linechars = [| '|' |]
            lineOptions = Map.empty }
          { orientation = Vertical
            gridCoordStart =
              { col = 22
                row = 3 }
            gridCoordEnd =
              { col = 22
                row = 4 }
            linechars = [| '|'; '|' |]
            lineOptions = Map.empty }
          { orientation = Vertical
            gridCoordStart =
              { col = 41
                row = 1 }
            gridCoordEnd =
              { col = 41
                row = 1 }
            linechars = [| '|' |]
            lineOptions = Map.empty }
          { orientation = Vertical
            gridCoordStart =
              { col = 41
                row = 3 }
            gridCoordEnd =
              { col = 41
                row = 4 }
            linechars = [| '|'; '|' |]
            lineOptions = Map.empty }
          { orientation = Vertical
            gridCoordStart =
              { col = 60
                row = 1 }
            gridCoordEnd =
              { col = 60
                row = 1 }
            linechars = [| '|' |]
            lineOptions = Map.empty }
          { orientation = Vertical
            gridCoordStart =
              { col = 60
                row = 3 }
            gridCoordEnd =
              { col = 60
                row = 4 }
            linechars = [| '|'; '|' |]
            lineOptions = Map.empty } |])

    let lineScanResult = (horizLines, vertLines) = allLinesExpected && allLinesExpected = allLines